name: deploy
on:
  workflow_dispatch:
  push:
    branches:
    - marster
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run Ansible playbook
      # You may pin to the exact commit or the version.
      # uses: dawidd6/action-ansible-playbook@5d970176ea4bfd99a3f5004d48e293fe0994eda1
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secret.SSH_KEY }}
        host: ${{ secret.HOST }}
        username: ${{ secret.USER }}
        script: |
          cd /etc/ansible/playbook
          ansible-playbook arkinfo-deploy-role.yml
        
